#!/bin/sh
#
# This script exits the container in case of 
# any essential program fails. 
#

if test -p /var/run/svcfinish/control
then
    exec 8<>/var/run/svcfinish/control
    echo "exit ${PWD} $1 $2" >&8
fi

exit 1
